{"error":"    at new CustomError (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\misc\\Error.js:7:14)\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\services\\AuthenticationService.js:74:37\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\model.js:3949:16\n    at Immediate.<anonymous> (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\query.js:1516:14)\n    at Immediate.<anonymous> (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mquery\\lib\\utils.js:119:16)\n    at runCallback (timers.js:794:20)\n    at tryOnImmediate (timers.js:752:5)\n    at processImmediate [as _immediateCallback] (timers.js:729:5)","level":"error","message":"BadRequest","timestamp":"2018-05-21T15:41:36.514Z"}
{"error":"    at new CustomError (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\misc\\Error.js:7:14)\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\services\\AuthenticationService.js:82:23\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\model.js:3949:16\n    at process.nextTick (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\query.js:2016:28)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","level":"error","message":"BadRequest","timestamp":"2018-05-21T15:41:57.545Z"}
{"error":"    at new CustomError (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\misc\\Error.js:7:14)\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\services\\AuthenticationService.js:74:37\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\model.js:3949:16\n    at Immediate.<anonymous> (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\query.js:1516:14)\n    at Immediate.<anonymous> (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mquery\\lib\\utils.js:119:16)\n    at runCallback (timers.js:794:20)\n    at tryOnImmediate (timers.js:752:5)\n    at processImmediate [as _immediateCallback] (timers.js:729:5)","level":"error","message":"BadRequest","timestamp":"2018-05-21T15:44:13.818Z"}
{"error":"    at new CustomError (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\misc\\Error.js:7:14)\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\services\\AuthenticationService.js:82:23\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\model.js:3949:16\n    at process.nextTick (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\query.js:2016:28)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","level":"error","message":"BadRequest","timestamp":"2018-05-21T15:44:18.262Z"}
{"error":"    at new CustomError (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\misc\\Error.js:7:14)\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\services\\AuthenticationService.js:82:23\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\model.js:3949:16\n    at process.nextTick (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\query.js:2016:28)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","level":"error","message":"BadRequest","timestamp":"2018-05-21T15:46:08.851Z"}
{"error":"    at new CustomError (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\misc\\Error.js:7:14)\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\services\\AuthenticationService.js:82:23\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\model.js:3949:16\n    at process.nextTick (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\query.js:2016:28)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","level":"error","message":"BadRequest","timestamp":"2018-05-21T15:46:20.691Z"}
{"error":"    at new CustomError (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\misc\\Error.js:7:14)\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\services\\AuthenticationService.js:82:23\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\model.js:3949:16\n    at process.nextTick (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\query.js:2016:28)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","level":"error","message":"BadRequest","timestamp":"2018-05-21T15:46:21.846Z"}
{"error":"    at new CustomError (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\misc\\Error.js:7:14)\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\services\\AuthenticationService.js:146:13\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\model.js:3949:16\n    at process.nextTick (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\query.js:2016:28)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","level":"error","message":"InvalidRequest","timestamp":"2018-05-21T16:08:34.040Z"}
{"error":"    at new CustomError (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\misc\\Error.js:7:14)\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\services\\AuthenticationService.js:146:13\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\model.js:3949:16\n    at process.nextTick (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\query.js:2016:28)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","level":"error","message":"InvalidRequest","timestamp":"2018-05-21T16:10:27.858Z"}
{"error":"    at new CustomError (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\misc\\Error.js:7:14)\n    at AuthenticationService.authenticate (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\services\\AuthenticationService.js:124:9)\n    at Layer.handle [as handle_request] (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\express\\lib\\router\\route.js:131:13)\n    at Route.dispatch (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\express\\lib\\router\\index.js:277:22\n    at Function.process_params (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\express\\lib\\router\\index.js:330:12)\n    at next (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\express\\lib\\router\\index.js:271:10)\n    at Function.handle (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\express\\lib\\router\\index.js:176:3)\n    at router (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\express\\lib\\router\\index.js:46:12)\n    at Layer.handle [as handle_request] (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\express\\lib\\router\\index.js:312:13)\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\express\\lib\\router\\index.js:280:7\n    at Function.process_params (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\express\\lib\\router\\index.js:330:12)\n    at next (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\express\\lib\\router\\index.js:271:10)","level":"error","message":"InvalidRequest","timestamp":"2018-05-21T16:11:02.324Z"}
{"error":"    at new CustomError (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\misc\\Error.js:7:14)\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\services\\AuthenticationService.js:150:13\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\model.js:3949:16\n    at process.nextTick (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\query.js:2016:28)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","level":"error","message":"InvalidRequest","timestamp":"2018-05-21T16:16:25.779Z"}
{"error":"    at new CustomError (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\misc\\Error.js:7:14)\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\services\\AuthenticationService.js:82:23\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\model.js:3949:16\n    at process.nextTick (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\query.js:2016:28)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","level":"error","message":"BadRequest","timestamp":"2018-05-21T16:17:57.036Z"}
{"error":"    at new CustomError (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\misc\\Error.js:7:14)\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\services\\AuthenticationService.js:151:13\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\model.js:3949:16\n    at process.nextTick (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\query.js:2016:28)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","level":"error","message":"InvalidRequest","timestamp":"2018-05-21T16:21:15.887Z"}
{"error":"    at new CustomError (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\misc\\Error.js:7:14)\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\app\\services\\AuthenticationService.js:83:23\n    at C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\model.js:3949:16\n    at process.nextTick (C:\\Users\\sfast\\Documents\\IMT18\\project\\server\\node_modules\\mongoose\\lib\\query.js:2016:28)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","level":"error","message":"BadRequest","timestamp":"2018-05-21T16:24:24.009Z"}
